# Generated by Django 2.0 on 2018-01-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0002_auto_20180111_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title_id',
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
