# Generated by Django 2.0 on 2018-01-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0003_auto_20180111_0528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
